# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN',
            fields=[
                ('AdminID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('AdminEmail', models.EmailField(max_length=254)),
                ('AdminPasswd', models.CharField(max_length=200)),
                ('AdminName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='QC_FORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerID', models.IntegerField()),
                ('QC_ID', models.IntegerField()),
                ('Quality', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('UserID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserPasswd', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=10)),
                ('UserRemark', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WORK_FORM',
            fields=[
                ('Work_FormID', models.IntegerField(primary_key=True, serialize=False)),
                ('Work_FormName', models.CharField(max_length=20)),
                ('WorkerID', models.IntegerField()),
                ('Date', models.DateField(null=True)),
                ('DES', models.TextField(max_length=200)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ORDER',
            fields=[
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='head.USER')),
                ('OrderName', models.CharField(max_length=10, null=True)),
                ('OrderID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('DATE_R', models.DateField(null=True)),
                ('DATE_D', models.DateField(null=True)),
                ('DES', models.TextField(null=True)),
                ('Price', models.IntegerField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='qc_form',
            name='Work_FormID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.WORK_FORM'),
        ),
        migrations.AddField(
            model_name='work_form',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.ORDER'),
        ),
    ]
