# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('UserPasswd', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=10)),
                ('UserRemark', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order_form',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.user'),
        ),
    ]
