# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20160527_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='AdminID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserEmail',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(),
        ),
    ]
