# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0002_auto_20160526_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Worker_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
    ]
