# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20160526_0719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userform',
        ),
    ]
