# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0003_auto_20160528_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
    ]
