# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import head.models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_auto_20160526_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='workFORM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkerID', models.IntegerField(verbose_name=head.models.Order)),
            ],
        ),
    ]
