# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0004_remove_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOODS',
            fields=[
                ('GoodID', models.IntegerField(primary_key=True, serialize=False)),
                ('GoodImage', models.ImageField(null=True, upload_to='')),
                ('GoodPrice', models.IntegerField()),
                ('GoodDetail', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='DATE_R',
        ),
        migrations.AlterField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
