# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0005_workform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='UserID',
            field=models.IntegerField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
