# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_auto_20160614_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ADDRESS',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='AdminEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
