# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0006_userform_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='UserID',
            field=models.IntegerField(default=0),
        ),
    ]
