# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20160526_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='OrderID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='WorkerID',
            field=models.IntegerField(default=0),
        ),
    ]
