# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0007_auto_20160615_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='GoodColor',
            field=models.CharField(default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='goods',
            name='GoodName',
            field=models.CharField(default='  ', max_length=20),
        ),
        migrations.AddField(
            model_name='goods',
            name='GoodWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='GoodImage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='ADDRESS',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
