# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0008_auto_20160526_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='DATE_D',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='DATE_R',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='DES',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workform',
            name='WorkName',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='UserID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workform',
            name='WorkerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='head.Order'),
        ),
    ]
