# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0008_auto_20160616_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Telephone',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
