# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('head', '0010_auto_20160616_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
